### PR TITLE
Add Player Interface

### LINKED ISSUE #22: Player Interface
Other than PneumaticCraft I don't know of very many mods that add a player interface block. It's kind of something that would be pretty practical to have around, but some packs \*cough\**Infinity*\*cough* don't include PneumaticCraft.

I think it would be cool to have one, it should also have a GUI where you can select what slots should be exposed.

A few other cool stuff that could be added would be:

- Charging items - Make it accept RF to charge items in the player's inventory. The charge should be round-robin
- Feeding the player - Make it accept Nutrient Distillation (EnderIO) or an equivalent (Pre-Chewed Food) from Practicalities. It would use maybe 100mb per shank. Always topping off both hunger and saturation.

Pre-chewed food should be created by putting water and two or more different food items into an Industrial Masher, which would create Pre-Chewed Food based on the average hunger+saturation of the two foods.

### PR DESCRIPTION
**Pull request by thecodewarrior**
Adds the player interface, which wraps the player's inventory in a block. Fixes #22 

Haven't tested in multiplayer, so yeah. Don't know if it'll work. But it's 1:30 am here and I'm tired.

### CODE REVIEW

**Comment by joekaiser** [comment]
This looks good, but I am not sure the user experience is the best :/

Put down a hopper and then one of these blocks on top of it. As soon as you bind it to yourself, the hopper starts to pull your entire inventory. Using the other PR you submitted I could form a chain and limit to certain inventory slots, but it seems a little cumbersome.

Just a few idea I want to chat about before I merge it in:

1. What if it ignored the hotbar? That way your sword, pick, etc..wouldn't run the risk of being put away
2. Maybe the Slot Filter block should take a Filter Card to *Whitelist* what can be grabbed. That way, Users have to be specific about what they want.

For example: I am out mining and want all ores and stone to be sent back home. I can bind a player interface to myself, and attach a slot filter so only slots 0-9 are sucked into my AE system. What if I accidentally put my food, torches, or something else in one of those slots? Being able to configure "slots 0-9 as long as they are iron, gold, diamond, lapis, cobble, etc" would be safe. But maybe you didn't intend it to be used like that?

(BTW, a quick test in MP didn't crash anything. I as able to transfer my inventory to a chest just fine by using a hopper attached to the block)

**Comment by thecodewarrior** [comment]
Ignoring the hotbar makes sense. I think it shouldn't have a filter for two reasons, you can filter most forms of item transport, and it'll be a pain.

The MP test I haven't run is if it'll latch onto the player when they log back in correctly.

**Comment by thecodewarrior** [comment]
Maybe I should instead add a filter card to the ~~Slot~~ Inventory Filter. That makes more sense.

**Comment by joekaiser** [comment]
>Maybe I should instead add a filter card to the Slot Inventory Filter. That makes more sense

Sorry, yeah that is what I was referring to. That doesn't have to happen for this to merge in. It was just a thought. I do think that this should ignore the hotbar though..unless you think the Card on the Inventory Filer would solve it better

**Comment by thecodewarrior** [comment]
I can't think of any reason why you would want to pull out of the hotbar, so I'll get on that soon.

**Pull request merged**
