### PR TITLE
The mega huge refactor-feature-utility pull request

### PR DESCRIPTION
**Pull request by thecodewarrior**
So I made a ton of changes:

Systems
- Added a system for making multiblocks
- Added a system for rendering static .obj models
- Added dynamic flair system

Features
- Added Tesla Coil – Medium range, low throughput, lossy (10 for 8), cheap wireless energy transfer
- Added Field Repeater – Tesla Coils will feed this with a 10 for 9 loss. This will then transmit to nearby Induction Coils
- Added Induction Coil – Receives 8 rf/t from Tesla Coils & Field Repeaters
- Changed the Imbued Tool to place fake torches (no item drops) when right-clicked

Multiblock & rendering system: Pretty simple yet complex to explain. just look at the code, it's pretty clear.

Flair system:
- `flair.NAME=The flair text` for one line
- `flair.NAME.0=First line` and `flair.NAME.1=Second line` for multiple lines

### CODE REVIEW

**Comment by thecodewarrior** [comment]
If you can't tell, I use interfaces a lot. Abstraction! YAY!

**Comment by joekaiser** [comment]
Holy changelog, Batman!

This will take a bit to look through and sort out. Can't wait to see it all in action!

**Comment by joekaiser** [comment]
I trust you :P

**Comment by thecodewarrior** [comment]
Bwahahaha! He missed the virus I added!

**Pull request merged**
